config/routes.rb
Rails.application.routes.draw do
  root 'post#index'
  get 'post/index'

  get '/index', to: 'post#index'
  get '/new_post', to: 'post#new'
  post '/new_post', to: 'post#create'
  get '/post/:id', to: 'post#show', as: :post_show
  get 'post/:id/edit', to: 'post#edit', as: :post_edit
  patch '/post/:id/edit', to: 'post#update'
  delete 'delete/:id', to: 'post#destroy', as: :post_delete





  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :description, presence: true

  validates :description, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_index_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    puts @post
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_show_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to post_index_path
  end


  private
  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/edit.html.erb
<h1>Edit Post</h1>


<%= form_with model: @post, url: post_edit_path do |f|%>
  <%= f.label "Title:" %>
  <%= f.text_field :title %> <br>
  <%= f.label "Description" %>
  <%= f.text_field :description %> <br>
  <%= f.submit %>
<% end %>

app/views/post/index.html.erb
<h1>Hello World</h1>
<p>This is my test app for a Rails app</p>

<% @posts.each do |post|%>
  <p>
    <%= post.title %> <br>
    <%= link_to "show more", post_show_path(post.id) %>
  </p>
<% end %>

app/views/post/new.html.erb
<h1>Post</h1>

<%= form_with model: @post, url: new_post_path do |f|%>
  <%= f.label "Title:" %>
  <%= f.text_field :title %> <br>
  <%= f.label "Description" %>
  <%= f.text_field :description %> <br>
  <%= f.submit %>
<% end %>

app/views/post/show.html.erb
<h1><%=@post.title %></h1>
<p><%=@post.description %></p>

<%= link_to "Edit", post_edit_path(@post) %>
<%= link_to "Delete", post_delete_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>